### PR TITLE
add support for custom injector creation, fixes issue #1

### PR DESCRIPTION
**Pull request by twicksell**
Added a way to hook into the creation of the injector for bridging to things like Governator.

### CODE REVIEW

**Comment by dsyer** [comment]
I guess this could be useful. Can we have a test, please?

**Comment by twicksell** [comment]
It does. Useful for anyone who needs a custom version of the injector (like Governator). Adding a test now, but do you have any suggestions for handling multiple implementations of the InjectorFactory?

**Comment by twicksell** [comment]
Fixed. Throwing an exception to break startup if multiple definitions are found

**Comment by twicksell** [comment]
Hey @dsyer would you mind giving this a merge?

**Comment by dsyer** [comment]
Merged in 8fd316c

**Comment by dsyer** [comment]
@twicksell are you using this project? If it's useful we could do a proper release in Maven Central.

**Comment by twicksell** [comment]
Thanks for the merge! We are using this project with some renewed focus now and would greatly appreciate a Maven release. However, I've got at least one more PR for https://github.com/spring-projects/spring-guice/issues/12 that I would like to have done before a final release.

**Pull request closed without merging**
